Parameters:
  InstanceType:
      Description: WebServer EC2 instance type
      Type: String
      Default: t3.small
  ImageId:
      Description: ami value
      Type: String
      Default: ami-01a4f99c4ac11b03c
Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref 'ImageId'
      KeyName: "mumbai"
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
      - launch-wizard-2
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            echo ?Hello World from $(hostname -f)? > /var/www/html/index.html
  EC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref 'ImageId'
      KeyName: "mumbai"
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
      - launch-wizard
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            echo ?Hello World from $(hostname -f)? > /var/www/html/index.html
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
      
